### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mateen-pz** [MIRACLE-Center/CTSpine1K#11]
hello!!
hope you will be fine i have a issue when i run the Task056_VerSe2019.py the .pkl  is created after that it raise error .....

Traceback (most recent call last):
  File "Task056_VerSe2019.py", line 127, in <module>
    shutil.copy(image_file, join(imagestr, p + "_0000.nii.gz"))
  File "/home/projectz-pc2/anaconda3/envs/yolov5_env/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/projectz-pc2/anaconda3/envs/yolov5_env/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/media/projectz-pc2/Development/Mateen/CTSpine1K-main/nnUNet/dataset_corrOrient/train/1.3.6.1.4.1.9328.50.4.0001.nii.gz'
plz help me to fix it
thank you

**Comment by Sungden** [comment]
It seems that your file folder is wrong. You can check it as the error suggested.

**Comment by mateen-pz** [comment]
dataset contain the seg.nii.gz file not .nii.gz
