### ISSUE TITLE
label errors

### ISSUE THREAD

**Issue by BigPandaCPU** [MIRACLE-Center/CTSpine1K#13]
Hi,SungDen

Thank you for providing such an amazing dataset,I found there are some errors about the label.
1.Spacing error.
![spacing_error](https://user-images.githubusercontent.com/25834151/218015395-3aa095b9-37e3-412b-9578-8e8890f59419.png)

![spacing_compare](https://user-images.githubusercontent.com/25834151/218015809-2b6191af-adf7-401a-8ac1-0947547595a9.png)

2.label not continue.
(1)1.3.6.1.4.1.9328.50.4.0103_seg.nii.gz 
![103](https://user-images.githubusercontent.com/25834151/218016343-6cc354dd-bd93-4492-aef1-d5b0ac4a9348.png)

(2)1.3.6.1.4.1.9328.50.4.0291.nii.gz  loss label22.
![image](https://user-images.githubusercontent.com/25834151/218016486-8ca6feb9-aac5-421e-99a3-85b93fa7f0c7.png)

(3)1.3.6.1.4.1.9328.50.4.0730.nii.gz  loss label22.
![image](https://user-images.githubusercontent.com/25834151/218016589-3addbb20-658b-4097-97b6-eb304c017444.png)

**Comment by Sungden** [comment]
Thanks for your pointing out these mistakes. Could you provide these correct annotations to me and I will upload them to google drive and Baiduyun?

**Comment by BigPandaCPU** [comment]
Sorry,I don't have the correct annotations, I just exclude the wrong annotation data while training.
