### ISSUE TITLE
Mistake labeled mask

### ISSUE THREAD

**Issue by sunshichen** [MIRACLE-Center/CTSpine1K#15]
Thanks greatly for your contributions with this dataset.
I found a suspicious mask in 
`colon/1.3.6.1.4.1.9328.50.4.0482.nii.gz`
Thought it would be label 15 rather than 14 on the top slices.

![1694080878745](https://github.com/MIRACLE-Center/CTSpine1K/assets/23454839/44c581bd-6b99-4eae-a7e0-566539fda4ac)

Same mistake also:
`colon/1.3.6.1.4.1.9328.50.4.0500.nii.gz`

**Comment by Sungden** [comment]
Thanks! Please give me the corrected annotations if you did it so that I update them.
